name:  fetchs a file
run-name: Fetchs a file 

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "System to run the script on"
        options:
          - qa
          - playground
          - staging
          - production
      csv_path_in_s3:
        default: ''
        required: false
        type: string
        description: "CSV path in s3 to resume from"

jobs:
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Print environment
        run: echo "Running on env: ${{ github.event.inputs.env }}"

      - name: Print CSV path
        run: echo "CSV path: ${{ github.event.inputs.csv_path_in_s3 }}"
