name: Fetch a file
run-name: Fetch a file

on:
  workflow_dispatch:
    inputs:
      env:
        description: "System to run the script on"
        required: true
        type: choice
        options:
          - qa
          - playground
          - staging
          - production

      csv_path_in_s3:
        description: "CSV path in s3 to resume from"
        required: false
        default: ''
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Print environment
        run: echo "Running on env: ${{ github.event.inputs.env }}"

      - name: Print CSV path
        run: echo "CSV path: ${{ github.event.inputs.csv_path_in_s3 }}"
